version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Automatized database migration"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
